import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./components/NavBar";
import ThreeCanvas from "./components/ThreeCanvas";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Enigma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Navbar />
        <main className={styles.main}>
          <h2 className={styles.mainText}>
            Are you brave enough to face your deepest fears?
          </h2>
          <div>
            <ThreeCanvas />
          </div>
          <p className={styles.secondText}>
            {" "}
            Inside our mystery boxes, you will find objects that will take you
            to the darkest corners of the human mind. Can you handle the weight
            of their macabre stories? From ancient relics that are rumored to be
            haunted, to disturbing objects from unsolved crimes. Do you dare to
            venture into the darkness and uncover the mysteries that lie within
            our mystery boxes? But be careful, what you find may be more
            terrifying than you ever imagined.
          </p>
        </main>
      </div>
    </>
  );
}
